
CREATE TABLE EVENTO (
                ID_EVENTO BIGINT IDENTITY NOT NULL,
                CATEGORIA VARCHAR(50) NOT NULL,
                TITULO VARCHAR(150) NOT NULL,
                TEXTO VARCHAR(8000) NOT NULL,
                IMAGEM VARCHAR(50),
                IMAGEM_APARECER_DETALHE CHAR(1),
                DATA_PUBLICACAO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT EVENTO_pk PRIMARY KEY (ID_EVENTO)
)
CREATE UNIQUE  NONCLUSTERED INDEX EVENTO_idx
 ON EVENTO
 ( TITULO )

/*
CREATE TABLE USUARIO (
                ID_USUARIO BIGINT IDENTITY NOT NULL,
                CPF VARCHAR(11) NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                SENHA VARCHAR(20) NOT NULL,
                CONSTRAINT USUARIO_pk PRIMARY KEY (ID_USUARIO)
)
CREATE UNIQUE  NONCLUSTERED INDEX USUARIO_idx
 ON USUARIO
 ( CPF )
*/