
CREATE TABLE USUARIO (
                ID_USUARIO INT IDENTITY NOT NULL,
                CPF VARCHAR(11) NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                SENHA VARCHAR(20) NOT NULL,
                CONSTRAINT USUARIO_pk PRIMARY KEY (ID_USUARIO)
)
CREATE UNIQUE  NONCLUSTERED INDEX USUARIO_idx
 ON USUARIO
 ( CPF )


CREATE TABLE EVENTO (
                ID_EVENTO BIGINT IDENTITY NOT NULL,
                CATEGORIA VARCHAR(50) NOT NULL,
                TITULO VARCHAR(100) NOT NULL,
                TEXTO VARCHAR(8000) NOT NULL,
                IMAGEM VARCHAR(50),
                DATA_PUBLICACAO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
                ID_USUARIO INT NOT NULL,
                CONSTRAINT EVENTO_pk PRIMARY KEY (ID_EVENTO)
)
CREATE UNIQUE  NONCLUSTERED INDEX EVENTO_idx
 ON EVENTO
 ( TITULO )


ALTER TABLE EVENTO ADD CONSTRAINT USUARIO_NOTICIA_fk
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID_USUARIO)
ON DELETE NO ACTION
ON UPDATE NO ACTION